### ISSUE TITLE
Some examples will be outdated when 0.11 comes out

### ISSUE THREAD

**Issue by Adamkob12** [PROMETHIA-27/dependency_injection_like_bevy_from_scratch#2]
Hey, I'm reading the book right now and it's awesome!
Just wanted to mention that in 0.11
.add_system(..) and .add_startup_system(..)
will be deprecated in favor of
.add_systems(Update, ..), add_systems(Startup, ..)
There are probably more but these are the main ones.

**Comment by PROMETHIA-27** [comment]
Cool, thanks for letting me know! I'll try to remember to update them when it releases.
